export const statusTimelineStyles = {
  list: 'flex flex-col gap-y-3',
  item: 'flex flex-col gap-y-1.5',
  chainPath: 'flex items-center gap-x-2',
  nav: 'overflow-x-auto',
  navDefaultHeight: 'h-20',
  navTallHeight: 'h-24',
  navList: 'flex items-center',
  stepWrapper: 'relative',
  stepSpacing: 'pr-16 sm:pr-24',
  stepCircleBase:
    'relative flex h-8 w-8 items-center justify-center rounded-full',
  stepCircleSuccess:
    'bg-blue-600 hover:bg-blue-700 dark:bg-blue-500 dark:hover:bg-blue-400',
  stepCircleFailed:
    'bg-red-600 hover:bg-red-700 dark:bg-red-500 dark:hover:bg-red-400',
  stepLabel: 'absolute mt-1 whitespace-nowrap text-2xs font-medium',
  stepLabelSuccess: 'text-blue-600 dark:text-blue-500',
  stepLabelFailed: 'text-red-600 dark:text-red-500',
  shortTitleSpacing: 'ml-1',
  expressLabelWrapper: 'absolute mt-3',
  expressLabel: 'text-2xs font-medium text-green-600 dark:text-green-500',
  hopLinkWrapper: 'absolute mt-6',
  hopLink:
    'whitespace-nowrap rounded-md border border-blue-600 px-2 py-1.5 text-base font-semibold text-blue-600 dark:border-blue-500 dark:text-blue-500',
  connectorWrapper: 'absolute inset-0 flex items-center',
  connectorLineBase: 'h-0.5 w-full',
  connectorLineSuccess: 'bg-blue-600 dark:bg-blue-500',
  connectorLineFailed: 'bg-red-600 dark:bg-red-500',
  pendingConnectorLine: 'bg-zinc-200 dark:bg-zinc-700',
  pendingCircle:
    'relative flex h-8 w-8 items-center justify-center rounded-full border-2 bg-zinc-50 dark:bg-zinc-800',
  pendingBorderDefault: 'border-zinc-200 dark:border-zinc-700',
  pendingBorderActive: 'border-blue-600 dark:border-blue-500',
  pendingClock: 'h-5 w-5',
  pendingLabel: 'absolute mt-12 whitespace-nowrap pt-1 text-2xs font-medium',
  pendingLabelActive: 'text-blue-600 dark:text-blue-500',
  pendingLabelInactive: 'text-zinc-400 dark:text-zinc-500',
  pendingTimeWrapper: 'absolute mt-20',
  pendingTimeText: 'ml-1 text-2xs !font-medium',
  warningRow: 'flex items-center gap-x-1 text-red-600 dark:text-red-500',
  warningText: 'text-xs',
} as const;
