export const infoStyles = {
  container:
    'overflow-hidden bg-zinc-50/75 shadow dark:bg-zinc-800/25 sm:rounded-lg',
  header: 'px-4 py-6 sm:px-6',
  headerTitle:
    'text-base font-semibold leading-7 text-zinc-900 dark:text-zinc-100',
  headerSubtitle:
    'mt-1 max-w-2xl text-sm leading-6 text-zinc-400 dark:text-zinc-500',
  body: 'border-t border-zinc-200 dark:border-zinc-700',
  list: 'divide-y divide-zinc-100 dark:divide-zinc-800',
  section: 'px-4 py-6 sm:grid sm:grid-cols-4 sm:gap-4 sm:px-6',
  label: 'text-sm font-medium text-zinc-900 dark:text-zinc-100',
  value:
    'mt-1 text-sm leading-6 text-zinc-700 dark:text-zinc-300 sm:col-span-3 sm:mt-0',
  statusList: 'flex flex-col gap-y-3',
  statusItem: 'flex flex-col gap-y-1.5',
  tagBase: 'w-fit capitalize',
  pathRow: 'flex items-center gap-x-3',
  pathColumn: 'flex flex-col gap-y-2',
  warningRow: 'flex h-6 items-center gap-x-1.5 text-red-600 dark:text-red-500',
  settlementGrid:
    'flex flex-col gap-y-6 overflow-x-auto sm:grid sm:grid-cols-4 sm:gap-x-4 sm:gap-y-0',
  settlementColumn: 'flex justify-between gap-x-4',
  settlementColumnContent: 'flex flex-col gap-y-2 sm:gap-y-4',
  settlementColumnTitle:
    'whitespace-nowrap text-2xs font-medium text-blue-600 dark:text-blue-500',
  settlementLinks: 'flex flex-col gap-y-3',
  settlementValueSpacing: 'mt-4 sm:mt-1.5',
  recoveryList: 'flex flex-col gap-y-2',
  recoveryItem: 'grid w-72 grid-cols-3 gap-x-4',
  recoveryItemLabel: 'font-semibold capitalize',
  recoveryItemValue: 'col-span-2 flex items-center',
  toggleContainer: 'px-4 pb-4 sm:px-6',
  toggleButton:
    'flex items-center gap-x-1 text-xs font-medium text-blue-600 dark:text-blue-500',
  transferList: 'flex flex-col gap-y-1.5',
  transferRow: 'flex items-center gap-x-1',
  assetChip: 'h-6 w-fit rounded-xl bg-zinc-100 px-2.5 py-1 dark:bg-zinc-800',
  arrowIcon: 'text-zinc-700 dark:text-zinc-300',
  tokenRow: 'flex items-center gap-x-4',
  detailColumn: 'flex flex-col gap-y-2',
  timeRow: 'flex items-center gap-x-4',
  timeValueRow: 'flex items-center gap-x-1 text-zinc-400 dark:text-zinc-500',
  timeExpressRow:
    'flex items-center gap-x-1 text-green-600 dark:text-green-500',
  warningRowTall:
    'flex h-6 items-center gap-x-1.5 text-red-600 dark:text-red-500',
  labelInline: 'flex items-center gap-x-1',
  inlineInfoTooltip: 'w-40 text-xs',
  tooltip: 'whitespace-nowrap',
  profileColumn: 'flex flex-col gap-y-2',
  iconButton: 'font-semibold text-blue-600 dark:text-blue-500',
  flexRow: 'flex items-center gap-x-1',
  inlineNumber: 'font-medium',
  inlineNumberMuted: 'font-normal text-zinc-400 dark:text-zinc-500',
  inlineLabel: 'whitespace-nowrap text-xs text-zinc-700 dark:text-zinc-300',
  borderedCard: 'flex items-center gap-x-4 overflow-x-auto',
  infoIcon: 'text-zinc-400 dark:text-zinc-500',
  plusIcon: 'text-zinc-400 dark:text-zinc-500',
  detailsGrid: 'grid gap-4 py-4',
  detailsGridTwoCols: 'md:grid-cols-2',
} as const;
